### ISSUE TITLE
script needs to wipe all partitions if the drive is not formatted

### ISSUE THREAD

**Issue by tim0n3** [ChrisTitusTech/ArchTitus#141]
the script fails to execute if there are partitions from a previous installation.

The workaround, for now, is to use the disk tool, parted, to wipe existing partitions followed by a reboot, and then you can run the script.

**Comment by nikkuuwux** [comment]
Yesterday I went from fully installed Skolelinux 12 BD directly to nvme to arch titus and it seems to have installed properly for me. I must have just dodged that--or I'm just lucky. 
I would just like to state that I know that I know nothing and I have no idea what is happening half the time.

**Comment by tim0n3** [comment]
> Yesterday I went from fully installed Skolelinux 12 BD directly to nvme to arch titus and it seems to have installed properly for me. I must have just dodged that--or I'm just lucky. I would just like to state that I know that I know nothing and I have no idea what is happening half the time. Regards, Nikku

Honestly not sure how to replicate this but I used a laptop that had Linux Mint (can't remember the exact version) and shutdown the laptop. Then I booted from the arch ISO and followed the installation guide (clone from git etc...) and the installation kept failing when trying to write the partition changes and then rebooted.

After I manually wiped the partitions using parted and rebooted could the script run and write the changes.

Could this have anything to do with the fact that the kernel can't update the disk partition scheme until a reboot is done? (that was the message I was getting from parted after wiping the drive)

**Comment by nikkuuwux** [comment]
> 

Interesting. Although im not too well versed with laptop hardware (from my extremely limted knowledge of how things usually differ between lapttops and pc hardware setups), one thing I do know about laptops is that they have alternate functionality concerning the power state "hibernation" and/or the possibility of a "hiber~boot"??? I really don't actually know, but my suggestion would be to investigate how your particular latops manufacturer and specific hardware BIOS handles: boot order, and hibernation.  

Just off the top of my noggin, my personal reccomendation would be to do a full shut down, power on computer into UEFI Arch iso (ensuring to see the gui archiso-boot screen rather than the legacy) and following with the usual. Which it seems you have already tried.

Good luck and Godspeed,
Nikkux

**Comment by ChrisTitusTech** [comment]
Fixed with new update
