### ISSUE TITLE
AUR packages not installing

### ISSUE THREAD

**Issue by yehonatan2020** [ChrisTitusTech/ArchTitus#168]
Something is wrong with the scripts, because all the pacman packages get installed, but it completes by enabling all the systemctl services etc but the aur packages dont get installed

**Comment by yehonatan2020** [comment]
runuser: -- does not exist or the user entry does not contain all the required fields

**Comment by Cosipa** [comment]
I have the same problem, and I would like to add that it only installs the aur packages when you manually type the username on 
`arch-chroot /mnt /usr/bin/runuser -u $username -- /home/$username/ArchTitus/2-user.sh` instead of $username. 

_So the issue seems to be that the source to setup.conf isn't working propperly past arch-chroot on the archtitus.sh_

**Comment by Zackptg5** [comment]
Think the issue is that the username variable is now uppercase. Try changing all instances of `$username` to `$USERNAME`
Looks like this is an issue in archtitus.sh and 3-post-setup.sh

**Comment by yehonatan2020** [comment]
Zackptg5 - you were 100 percent correct. changing $username to $USERNAME fixed it!!!

**Comment by ChrisTitusTech** [comment]
Thanks Fixed in main branch!
