### ISSUE TITLE
Can't make any changes in GRUB

### ISSUE THREAD

**Issue by igorw765** [ChrisTitusTech/ArchTitus#228]
Hi everyone,

At first everything looked just fine but now I get into trouble with grub. I'm not able to install any theme or another kernel. It's just not showing up in grub. I tried regenerating cfg file multiple times with grub customizer and with commands. I have no clue what can I do about that problem.
Thanks ;33

**Comment by mfgbhatti** [comment]
Hey,
What i understand from your question is that you installed arch using Archtitus. First everything was fine. But now it is not what you want it to do.
I don't think your question is about this script i think it is related to arch as OS or may be grub as bootloader.

**Comment by MarioShebib** [comment]
Would that also be the case for if you run the script and after removing the iso what you boot up into isn't the custom gui but instead a terminal screen that says GNU GRUB version 2.06?I wanted to try out ArchTitus on a VM and since I have my SSD on windows I used virtualbox.

It is probably something wrong on my end but I just tried to copy what Chris did in his video showcasing the installation process.

**Comment by ChrisTitusTech** [comment]
Fixed using @khaneliman new merge
