### ISSUE TITLE
How to create an ISO from the boot script

### ISSUE THREAD

**Issue by arlyxiao** [ChrisTitusTech/ArchTitus#311]
Obviously this is not an issue. It's just a question.

Anyone can share that how to build an ISO file?

**Comment by mehultw** [comment]
Would love to get an answer for this, I looked at system-back a debian based tool (which has lost support now) allowing users to create live linux images. Can't install that on Arch, if you can, let me know. 
If there are other ways to achieve this (scripts or apps) do let me know.

**Comment by rafay99-epic** [comment]
My friend to Build an Arch ISO you need to download the torrent file from the arch website.
## Download ISO File
1. The Link for the website is https://archlinux.org/download/
2. Once the torrent file is downloaded then using a program or online torrent converter download the Arch Linux ISO.
3. Once you have the ISO then flash the iso onto a USB drive.

## Flashing an ISO File:
1. In order to flash a USB with an ISO file there are multiple Programs that can be used. for example etcher.
2. Download any of the programs.
3. Run the application. Once, done then plug in your USB drive select your ISO file, and then press flash.
4. It will take 10 mins and you will have a bootable USB drive of arch Linux.

For more Information Follow this article: https://www.makeuseof.com/create-bootable-usb-drive-with-etcher-linux/

**Comment by mehultw** [comment]
I think there was a misinterpretation of the question.
What I want to know is now that I have a working system, and made my modifications post install, **How can I create an ISO image of the current Arch setup installed, including the modifications.** 
If not this, then **how can we create an installable ISO at the spot after our install script has done its magic**, and you booted to your new arch install with custom applications installed already. 
I recon the process to get to either ISO is the same, I failed to find a method to ISO a current install using Arch.

Thanks!~

**Comment by rafay99-epic** [comment]
oh....So if he want to save his setting or config files just write a script that can automate that task for him..Or better fork Arch Titus add your changes and then install arch Linux.
