### ISSUE TITLE
Boot Stuck Hybrid (Nvidia+Intel)

### ISSUE THREAD

**Issue by ostarch** [ChrisTitusTech/ArchTitus#42]
After the installation is complete, the boot screen got stucked, tried to uninstall Nvidia drivers but nothing worked for me. Plx help

**Comment by yoss85** [comment]
Thanx @wolfee182 that solved the problem for me. 

@jrock2004 - After installing what @wolfee182 indicated, I removed the old xorg.conf file under /etc/X11/ and copied /usr/share/optimus-manager.conf to /etc/optimusmanager/optimus-manager.conf. Reboot and that was it.
Check out this blog post https://e-leclercq.github.io/posts/2020/06/blog-post-2/

**Comment by jrock2004** [comment]
@yoss85 That did the trick. Wondering if there is a way to ask this question during install and install these packages

**Comment by wolfee182** [comment]
Since the install is trying to figure out what drivers to install, how can it be automatically detected?
Running: lspci -vnn | grep '\''[030[02]\]' gives me the VGA cards in my system. 

00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106M [GeForce RTX 2070 Mobile / Max-Q Refresh] [10de:1f14] (rev a1) (prog-if 00 [VGA controller])

So the script would need to check if there are multiple card and if so then install the drivers, plus:

optimus-manager
optimus-manager-qt

I am still learning linux command line  or i would try to put it together myself.

**Comment by DanielToubul** [comment]
> Here are the packages related to video drivers i have installed with my system that work:
> 
> * nvidia
> * nvidia-utils
> * mesa
> * optimus-manager
> * optimus-manager-qt
> 
> This is the only combination that i found that works on my NVidia/Intel Hybrid Laptop. Hope this helps.

but how do you install it after the installation "fails" ?

**Comment by wolfee182** [comment]
Most people should be able to switch TTY by pressing "CTRL + ALT+ and a F-key like F2". (Dont use F1, because the GUI should be on that already.) Then you should see a Text based login. 

You should be able to login and then use "yay -S <package name>" to install the package (for example: yay -S nvidia nvidia-utils mesa optimus-manager optimus-manager-qt)

**Comment by jrock2004** [comment]
@wolfee182  of it could just be a question that asks the user ID you have multiple

**Comment by DanielToubul** [comment]
> Thanx @wolfee182, that solved the problem for me.
> 
> @jrock2004 - After installing what @wolfee182 indicated, I removed the old xorg.conf file under /etc/X11/ and copied /usr/share/optimus-manager.conf to /etc/optimusmanager/optimus-manager.conf. Reboot and that was it. Check out this blog post https://e-leclercq.github.io/posts/2020/06/blog-post-2/

this one helped me the most. The blog post. 
I managed to remove the Xorg file and then optimus could manage the display and etc..

**Comment by ChrisTitusTech** [comment]
Try this now, it should be fixed.
